# Generated by Django 3.2.11 on 2022-02-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('IdEspecialidad', models.PositiveSmallIntegerField(default=5, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('IdExamen', models.PositiveSmallIntegerField(default=5, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.IntegerField()),
                ('Duracion', models.DurationField()),
                ('NroPreguntas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('IdPregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('Pregunta', models.CharField(max_length=3000)),
                ('IdEspecialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=35)),
                ('ApellidoPaterno', models.CharField(max_length=35)),
                ('ApellidoMaterno', models.CharField(max_length=35)),
                ('Sexo', models.CharField(choices=[('O', 'Otro'), ('F', 'Femenino'), ('M', 'Masculino')], default='O', max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('FechaNacimiento', models.DateField()),
                ('Usuario', models.CharField(max_length=50)),
                ('Contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('IdRespuesta', models.IntegerField(primary_key=True, serialize=False)),
                ('Respuesta', models.CharField(max_length=3000)),
                ('PreguntaAsociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasXExamenXUsuario',
            fields=[
                ('IdPreguntasXExamenXUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('IdExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.examen')),
                ('IdPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.pregunta')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasXExamenes',
            fields=[
                ('IdPreguntasXExamenes', models.IntegerField(primary_key=True, serialize=False)),
                ('IdExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.examen')),
                ('IdPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenesXUsuario',
            fields=[
                ('IdExamenesXUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('IdExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.examen')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenesXEspecialidad',
            fields=[
                ('IdExamenesXEspecialidad', models.IntegerField(primary_key=True, serialize=False)),
                ('IdEspecialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.especialidad')),
                ('IdExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.examen')),
            ],
        ),
    ]
