# Generated by Django 3.2.11 on 2022-02-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0002_auto_20220221_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ApellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ApellidoPaterno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='FechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Sexo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario',
        ),
    ]
