# Generated by Django 3.2.11 on 2022-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0004_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Usuario',
            field=models.CharField(default='correo@prueba.com', max_length=50),
            preserve_default=False,
        ),
    ]
