# Generated by Django 3.2.11 on 2022-03-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0005_auto_20220317_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ApellidoPaterno',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='FechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Sexo',
            field=models.CharField(choices=[('O', 'Otro'), ('F', 'Femenino'), ('M', 'Masculino')], default='O', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Usuario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
