# Generated by Django 3.2.11 on 2022-04-18 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0006_auto_20220317_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenesxusuario',
            name='IdExamen',
        ),
        migrations.RemoveField(
            model_name='examenesxusuario',
            name='IdUsuario',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='IdEspecialidad',
        ),
        migrations.RemoveField(
            model_name='preguntasxexamenes',
            name='IdExamen',
        ),
        migrations.RemoveField(
            model_name='preguntasxexamenes',
            name='IdPregunta',
        ),
        migrations.RemoveField(
            model_name='preguntasxexamenxusuario',
            name='IdExamen',
        ),
        migrations.RemoveField(
            model_name='preguntasxexamenxusuario',
            name='IdPregunta',
        ),
        migrations.RemoveField(
            model_name='preguntasxexamenxusuario',
            name='IdRespuesta',
        ),
        migrations.RemoveField(
            model_name='preguntasxexamenxusuario',
            name='IdUsuario',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='PreguntaAsociada',
        ),
        migrations.DeleteModel(
            name='ExamenesXEspecialidad',
        ),
        migrations.DeleteModel(
            name='ExamenesXUsuario',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='PreguntasXExamenes',
        ),
        migrations.DeleteModel(
            name='PreguntasXExamenXUsuario',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
