# Generated by Django 3.2.11 on 2022-04-18 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0007_auto_20220417_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('IdPregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('Pregunta', models.CharField(max_length=500)),
                ('OpcionA', models.CharField(max_length=200)),
                ('OpcionB', models.CharField(max_length=200)),
                ('OpcionC', models.CharField(max_length=200)),
                ('OpcionD', models.CharField(max_length=200)),
                ('RespuestaCorrecta', models.CharField(choices=[('A', 'OpcionA'), ('B', 'OpcionB'), ('C', 'OpcionC'), ('D', 'OpcionD')], max_length=10)),
                ('Explicacion', models.CharField(max_length=3000)),
                ('IdEspecialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasXExamenXUsuario',
            fields=[
                ('IdPreguntasXExamenXUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('IdExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.examen')),
                ('IdPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.pregunta')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasXExamenes',
            fields=[
                ('IdPreguntasXExamenes', models.IntegerField(primary_key=True, serialize=False)),
                ('IdExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.examen')),
                ('IdPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenesXUsuario',
            fields=[
                ('IdExamenesXUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('IdExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.examen')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenesXEspecialidad',
            fields=[
                ('IdExamenesXEspecialidad', models.IntegerField(primary_key=True, serialize=False)),
                ('IdEspecialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.especialidad')),
                ('IdExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.examen')),
            ],
        ),
    ]
