# Generated by Django 3.2.11 on 2022-04-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0008_examenesxespecialidad_examenesxusuario_pregunta_preguntasxexamenes_preguntasxexamenxusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='Pregunta',
            field=models.CharField(max_length=1500),
        ),
    ]
