# Generated by Django 3.2.11 on 2022-04-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0009_alter_pregunta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='OpcionA',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='OpcionB',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='OpcionC',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='OpcionD',
            field=models.CharField(max_length=500),
        ),
    ]
