# Generated by Django 3.2.11 on 2022-05-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0010_auto_20220417_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasxexamenxusuario',
            name='IdExamen',
        ),
        migrations.AddField(
            model_name='preguntasxexamenxusuario',
            name='IdExamenesXUsuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home_api.examenesxusuario'),
            preserve_default=False,
        ),
    ]
