# Generated by Django 3.2.11 on 2022-05-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0011_auto_20220502_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasxexamenxusuario',
            name='RespuestaSeleccionada',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
