# Generated by Django 3.2.11 on 2022-05-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0012_preguntasxexamenxusuario_respuestaseleccionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasxexamenxusuario',
            name='Correcta',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
