# Generated by Django 3.2.11 on 2022-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0013_preguntasxexamenxusuario_correcta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Edad',
            field=models.IntegerField(null=True),
        ),
    ]
