# Generated by Django 3.2.11 on 2022-05-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0014_usuario_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenesxusuario',
            name='PreguntasCorrectas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='examenesxusuario',
            name='TotalPreguntas',
            field=models.IntegerField(null=True),
        ),
    ]
